default: &default
  adapter: postgresql
  encoding: unicode
  # Use the username and password you set up in pgAdmin
  username: postgres
  password: 221IT105@aswin
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: my_app_production
  # In production, sensitive info is usually handled via ENV variables
  username: <%= ENV['MY_APP_DATABASE_USER'] %>
  password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>